apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  selector:
    matchLabels:
      app: webapi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: webapi-app
    spec:
      containers:
      - name: webapi
        image: lidorabo/docker_repo:intweb_{{version}}
        ports:
        - containerPort: 50000
